### ISSUE TITLE
Support for 1.19.3?

### ISSUE THREAD

**Issue by kristibektashi** [Trikzon/transparent#10]
## Feature Description

Minecraft 1.19.3 should be supported and not crash

**Comment by venaminecraft** [comment]
Hello, here is the crash log:

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.minecraft.client.font.GlyphAtlasTexture.<init>(GlyphAtlasTexture:29)
	at net.minecraft.client.font.FontStorage.getGlyphRenderer(FontStorage:163)
	at net.minecraft.client.font.BuiltinEmptyGlyph.bake(BuiltinEmptyGlyph:53)
	at net.minecraft.client.font.FontStorage.setFonts(FontStorage:53)
	at net.minecraft.client.font.FontManager.method_27540(FontManager:45)
	at net.minecraft.util.Util.make(Util:440)
	at net.minecraft.client.font.FontManager.<init>(FontManager:45)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:540)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by venaminecraft** [comment]
Hello @kristibektashi, the update for 1.19.3 and 1.19.4 is out:
https://legacy.curseforge.com/minecraft/mc-mods/transparent/files/4503227

**Comment by Trikzon** [comment]
I'm surprised that anyone follows my mods close enough to notice since I hadn't announced it anywhere yet.
Thank you for using my mod :D
