### ISSUE TITLE
Transparent Mod does not compatible with latest Ash API

### ISSUE THREAD

**Issue by SteveKunG** [Trikzon/transparent#16]
I've just install and download latest Ash API, the game crash when it is running.

Here is a crash report.
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-12-21 14:39:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'transparent'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/diontryban/ash/api/modloader/fabric/FabricClientModInitializer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.diontryban.ash.api.modloader.fabric.FabricClientModInitializer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna12692343694513983810.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		opus4j.dll
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.19041.3803 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1059335064 bytes (1010 MiB) / 1442840576 bytes (1376 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4617
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37583.13
	Virtual memory used (MB): 13333.95
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.2.1
		ash_api: Ash API 20.2.3-beta
		autoclicker-fabric: Auto Clicker 1.20.2-1.9.0-build.26
		bettercommandblockui: BetterCommandBlockUI 0.4.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 3.6.1+fabric-1.20.2
			tcdcommons: TCD Commons API 3.6+fabric-1.20.2
		betterthirdperson: Better Third Person 1.9.0
		bobby: Bobby 5.0.2
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		boostedbrightness: Boosted Brightness 2.2.1
		borderlessmining: Borderless Mining 1.1.9+1.20.2
		camerautils: Camera Utils 1.20.2-1.0.7
		chunky: Chunky 1.3.92
		clientpaintings: Client Paintings 1.3.0+1.20.2
			cicada: CICADA 0.4.4
		cloth-config: Cloth Config v12 12.0.113
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		craftpresence: CraftPresence 2.2.6
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
		daylightchangerstruggle: DaylightChangerStruggle 0.0.0
		debugify: Debugify 1.20.2+1.0
		elytra_physics: Elytra Physics 2.0
		enhancedblockentities: Enhanced Block Entities 0.9.1+1.20.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
			spruceui: SpruceUI 5.0.3+1.20.2
		entityculling: EntityCulling 1.6.3
		exordium: Exordium 1.2.1-mc1.20.2
		fabric-api: Fabric API 0.91.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.78+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.8+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+95a8ac51a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.11+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.9+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.44+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.12+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.15.1
			mixinextras: MixinExtras 0.3.1
		fallingleaves: Falling Leaves 1.15.4
		ferritecore: FerriteCore 6.0.1
		fluidvoidfading: Fluid Void Fading 1.1.3
		freecam: Freecam 1.2.1.1+1.20
		highlight: Highlight 2.0.1
			resourcefullib: Resourceful Lib 2.0.7
				com_teamresourceful_yabn: yabn 1.0.3
		horsestatsvanilla: Horse Stats Vanilla 4.5.0
			libgui: LibGui 9.0.0+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		ias: In-Game Account Switcher 8.0.2
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		indicatia: Indicatia 8.1.0
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.13
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ismputils: iSMPUtils 4.1.14
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.16.0
		lithium: Lithium 0.12.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		malilib: MaLiLib 0.17.0
		memoryleakfix: Memory Leak Fix 1.1.3
		minecartspawnerrevived: Minecart Spawner Revived 1.0.0
		minecraft: Minecraft 1.20.2
		minihud: MiniHUD 0.28.0
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 8.0.1
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		morecullingextra: More Culling Extra 1.1-1.20.1
		mousewheelie: Mouse Wheelie 1.13.3+mc1.20.2
			amecsapi: Amecs API 1.5.6+mc1.20.2
			coat: Coat 1.0.0-beta.21+mc1.20.2
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20.2
			tweed4_base: tweed4_base 1.7.1+mc1.20.2
			tweed4_data: tweed4_data 1.2.1+mc1.20.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20.2
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20.2
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20.2
		no_fog: No Fog 1.3.4+1.16.5-1.20.1
		noisium: Noisium 1.0.2+mc1.20.x
		nvidium: Nvidium 0.2.4-beta
		panorama_screens: Panorama Screens 1.0+fabric+mc1.20.2
		raised: Raised 3.1.0
		replayfov: ReplayFov 2.4
			com_ezylang_evalex: EvalEx 3.0.5
		replaymod: Replay Mod 1.20.2-2.6.14
		servertick: Server Tick 1.9
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		sheepconsistency: Sheep Consistency 1.0.4
		shulkerboxtooltip: Shulker Box Tooltip 4.0.7+1.20.2
		simplefog: Simple Fog Control 1.4.0
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		sodium: Sodium 0.5.5
		spark: spark 1.10.55
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		squidnoglitch: Squid No Glitch 1.0.2
		syncmatica: Syncmatica 1.20.2-0.3.11
		telepistons: Telepistons 1.1.3
		threadtweak: ThreadTweak 1.20.2-0.1.1
		transparent: Transparent 8.0.1+1.20.1
		tweakeroo: Tweakeroo 0.18.0
		unseencommands: Unseen Commands 1.0.2
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.2-2.4.32
		waveycapes: WaveyCapes 1.4.2
		worldedit: WorldEdit 7.3.0-beta-02+e11f161
		worldeditcui: WorldEditCUI 1.20.2+01
	JVM uptime in seconds: 22.278
	Launched Version: fabric-loader-0.15.1-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>
```

**Comment by Trikzon** [comment]
Transparent isn't on 1.20.2 yet. The version of Ash API that you are using is for 1.20.2. Breaking changes were made to Ash API between 1.20.1 and 1.20.2
